env: "local"

token_ttl: 1h
client_domen: "http://localhost:5173"

psql:
  username: "user"
  host: "postgres"
  port: "5432"
  dbname: "mydb"
  sslmode: "disable"

redis:
  address: redis:6379
  user: admin
  db: 0
  max_retries: 5
  dial_timeout: 10s
  timeout: 5s

http_server:
  server_port: "0.0.0.0:8040"
  timeout: 4s
  idle_timeout: 60s
  access_tokenTTL: 15m
  refresh_tokenTTL: 43200m

